### ISSUE TITLE
Make this shit do stuff.

### ISSUE THREAD

**Issue by JFKingsley** [brendanashworth/watcher#2]
See above.

**Comment by MadisonBarks** [comment]
C'mon Bobo.
Making shit not do stuff?
Really?

Okay, I had my fun.

**Comment by brendanashworth** [comment]
The user interface is the last thing that needs to be completed.

Basically I'm just looking around for an MVC framework lighter than Angular.js and very easy to use. I might resort to making my own with mustache.js.

**Comment by JFKingsley** [comment]
Just use angular :P

**Comment by MadisonBarks** [comment]
I told him to use Node + Sails...
But NOOOOOOOO.

SOMEONE'S too stubborn :P

**Comment by brendanashworth** [comment]
@captgreen1 thats the backend
@JFKingsley I think I won't use any framework - heres the frontend look so far: http://upimg.me/d3334b380814680ed0226dd8111f424b

**Comment by brendanashworth** [comment]
I think this is now fixed. The frontend is now Angular and the app is entirely functional.
