### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by MadisonBarks** [brendanashworth/watcher#3]
Okay, but seriously.
This only supports Linux and Unix. Maybe Mac.
No Windows.

I request Windows support. Plz.

**Comment by brendanashworth** [comment]
I have fixed the number of processors check to move to `os` rather than `nproc`, but there still remains a few file issues that I'm not sure whether or not they're able to be fixed easily.

I've also fixed the load average, but on Windows that will remain at 0.

**Comment by brendanashworth** [comment]
Quite a lot of the issues are due to the entire app being based for a bash / unix based computer. The mounting and disk systems for Windows are entirely different which will take a lot of work to rethink, and I personally don't have a Windows machine to test this on.

I'm not sure how this will turn out.

**Comment by MadisonBarks** [comment]
I can offer my Windows machines up as testing platforms.
As far as the disk systems, try and use OS.\* if you can.
It abstracts a lot for you.

**Comment by MadisonBarks** [comment]
When I can get around to it tomorrow, I'll try and get some things working with Windows, and create a pull request.

**Comment by brendanashworth** [comment]
As far as my small research went, there is no equivalent way with a node API to get the disk partitions in the system, so I'm not sure whether that is even possible.

**Comment by MadisonBarks** [comment]
Ahh, I know my way around Diskpart.
I can try and play around with that :P

**Comment by brendanashworth** [comment]
I may be able to test a little bit with my newfound Vagrant. Do you have any more updates on this?

**Comment by MadisonBarks** [comment]
Currently, I do not.
I'm busy with another project, so this has been put off to the side for
right now :P

We might be able to make a Python client for Windows monitoring, and just
implement ZeroMQ or something.

--Austin Bolstridge
Web Developer and Application Developer
Eagle Scout

**Comment by brendanashworth** [comment]
I would much rather we keep it all in one language, unless we created a daemon-only version in C, Go, or some fast language that compiles to a binary.

**Comment by MadisonBarks** [comment]
What about python byte code?
Honestly, Windows is a special creature, that requires special support.
And Python provides that support.

**Comment by brendanashworth** [comment]
I don't know python! :p The current app pretty much just reads files and executes commands, what does Python offer that Node doesn't?

**Comment by MadisonBarks** [comment]
Ability to read system variables on Windows that Node can't.

--Austin Bolstridge
Web Developer and Application Developer
Eagle Scout

**Comment by brendanashworth** [comment]
The only thing that needs to be ported now is disk partitioning usage stats.
