### ISSUE TITLE
Beautiful logging

### ISSUE THREAD

**Issue by brendanashworth** [brendanashworth/watcher#5]
Lets make logging beautiful.

**Comment by MadisonBarks** [comment]
First step for that is to support database-based logging.
Hopefully Redis or something like that.

**Comment by brendanashworth** [comment]
The logging library has now been written and is put into the program as per [this commit](https://github.com/boboman13/watcher.js/commit/355ad0dd8d98cd42cbb3807d488a7490716f6d03).

It looks like this:

![this](http://upimg.me/fdf213e65d2c2032c272ec5a9b7d75dc.png)

@captgreen1, I think that Redis would be a little bit of bloat for just a small logging thing. However, if you feel it should still be implemented, feel free to create a new issue.
